// Mocks generated by Mockito 5.1.0 from annotations
// in assignment/test/http_post_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:assignment/api/http/http_post.dart' as _i4;
import 'package:assignment/api/model/post.dart' as _i6;
import 'package:assignment/api/response/response_f_post.dart' as _i2;
import 'package:assignment/api/response/response_post.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetFollowedPosts_0 extends _i1.Fake implements _i2.GetFollowedPosts {
}

class _FakeGetPost_1 extends _i1.Fake implements _i3.GetPost {}

/// A class which mocks [HttpConnectPost].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpConnectPost extends _i1.Mock implements _i4.HttpConnectPost {
  MockHttpConnectPost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseurl =>
      (super.noSuchMethod(Invocation.getter(#baseurl), returnValue: '')
          as String);
  @override
  set baseurl(String? _baseurl) =>
      super.noSuchMethod(Invocation.setter(#baseurl, _baseurl),
          returnValueForMissingStub: null);
  @override
  String get token =>
      (super.noSuchMethod(Invocation.getter(#token), returnValue: '')
          as String);
  @override
  set token(String? _token) =>
      super.noSuchMethod(Invocation.setter(#token, _token),
          returnValueForMissingStub: null);
  @override
  _i5.Future<Map<dynamic, dynamic>> postImage(_i6.AddPost? postData) =>
      (super.noSuchMethod(Invocation.method(#postImage, [postData]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i5.Future<Map<dynamic, dynamic>>);
  @override
  _i5.Future<_i2.GetFollowedPosts> getFollowedPost() =>
      (super.noSuchMethod(Invocation.method(#getFollowedPost, []),
              returnValue:
                  Future<_i2.GetFollowedPosts>.value(_FakeGetFollowedPosts_0()))
          as _i5.Future<_i2.GetFollowedPosts>);
  @override
  _i5.Future<List<dynamic>> getPosts() =>
      (super.noSuchMethod(Invocation.method(#getPosts, []),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<List<dynamic>> getOtherPosts(String? user_id) =>
      (super.noSuchMethod(Invocation.method(#getOtherPosts, [user_id]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<List<dynamic>> getTaggedPosts() =>
      (super.noSuchMethod(Invocation.method(#getTaggedPosts, []),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<List<dynamic>> getOtherTaggedPosts(String? user_id) =>
      (super.noSuchMethod(Invocation.method(#getOtherTaggedPosts, [user_id]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i5.Future<List<dynamic>>);
  @override
  _i5.Future<_i3.GetPost> getSinglePost(String? post_id) =>
      (super.noSuchMethod(Invocation.method(#getSinglePost, [post_id]),
              returnValue: Future<_i3.GetPost>.value(_FakeGetPost_1()))
          as _i5.Future<_i3.GetPost>);
  @override
  _i5.Future<Map<dynamic, dynamic>> getSinglePostLC(String? post_id) =>
      (super.noSuchMethod(Invocation.method(#getSinglePostLC, [post_id]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i5.Future<Map<dynamic, dynamic>>);
  @override
  _i5.Future<Map<dynamic, dynamic>> updatePost(_i6.UpdatedPost? postData) =>
      (super.noSuchMethod(Invocation.method(#updatePost, [postData]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i5.Future<Map<dynamic, dynamic>>);
  @override
  _i5.Future<Map<dynamic, dynamic>> deletePost(String? post_id) =>
      (super.noSuchMethod(Invocation.method(#deletePost, [post_id]),
              returnValue:
                  Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
          as _i5.Future<Map<dynamic, dynamic>>);
}
